version: '3.7'

services:
  web:
    container_name: web_nginx
    image: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./airtalk-system:/var/www/html/airtalk-system
      - ./ready-to-sell-api:/var/www/html/ready-to-sell-api
      - ./airvoice-system:/var/www/html/airvoice-system
      - ./airtalk-api-v2:/var/www/html/airtalk-api-v2
      - ./cintex-system:/var/www/html/cintex-system
      - ./airtalk-api:/var/www/html/airtalk-api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      TZ: America/Chicago
    ports:
      - 3307:3306
    volumes:
      - ./db:/db
    networks:
      - net

  php:
    container_name: main
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./docker/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./airtalk-system:/var/www/html/airtalk-system
      - ./ready-to-sell-api:/var/www/html/ready-to-sell-api
      - ./airvoice-system:/var/www/html/airvoice-system
      - ./airtalk-api-v2:/var/www/html/airtalk-api-v2
      - ./cintex-system:/var/www/html/cintex-system
      - ./airtalk-api:/var/www/html/airtalk-api
    networks:
      - net
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - net

networks:
  net:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
